project_id = "jsqzkaarpfowgmijcwaw"

[functions.create-user]
verify_jwt = true

[functions.asset-service]
verify_jwt = true

[functions.work-order-service]
verify_jwt = true

[functions.inventory-service]
verify_jwt = true

[functions.api-gateway]
verify_jwt = true