project_id = "jsqzkaarpfowgmijcwaw"

[functions.superadmin-ai-chat]
verify_jwt = true

[functions.embed-organization-data]
verify_jwt = false

[functions.refresh-cost-insights]
verify_jwt = false

[functions.create-user]
verify_jwt = true

[functions.asset-service]
verify_jwt = true

[functions.work-order-service]
verify_jwt = true

[functions.work-order-service-enhanced]
verify_jwt = true

[functions.inventory-service]
verify_jwt = true

[functions.people-service]
verify_jwt = true

[functions.safety-service]
verify_jwt = true

[functions.job-plans-service]
verify_jwt = true

[functions.pm-schedules-service]
verify_jwt = true

[functions.notification-service]
verify_jwt = true

[functions.api-gateway]
verify_jwt = true

[functions.workflow-service]
verify_jwt = true